### PR TITLE
Run it in docker

### PR DESCRIPTION
**Pull request by mmatoscom**
we can add more args as well improve the code from here
still need to edit run.sh to update with our vars
and add more vars to be called on dockerfile
its working, opens chrome, logs in and deletes posts
your code is running on docker +_+
thanks for this code, I wanted to delete my stuff long ago
this is how I can give it back, cheers
Marco

### CODE REVIEW

**Comment by weskerfoot** [comment]
Thanks for working on this, I'll test it out as soon as I can

**Comment by weskerfoot** [comment]
I was able to build the image successfully

I'm going to merge and then probably see if I can do something with the new Github image registry.

**Comment by weskerfoot** [comment]
@mmatoscom Is `run.sh` necessary? Looks like it was just there for testing

**Comment by mmatoscom** [comment]
Hi, I made this run.sh to get people unfamiliar with Docker deleting posts right away. 
I also put this run.sh in the Dockerfile header. Docker does not need it, can be deleted. 
Still, need to:
- fix run vars (2FA delete by year, unlike pages, archival)
- I've made a Makefile, maybe helps somebody, `make build`, `make run`, prompts for facebook email, user, pass, (and 2FA, year, etc), exports them to container entrypoint. You can take a look at my fork to check. Its not fully functional, I am working on it. 
If you want I could help with some travis pipeline, testing etc

**Comment by mmatoscom** [comment]
I forgot to mention was thinking about to cherry pick only the final version with the Dockerfile and create a new PR

**Comment by weskerfoot** [comment]
@mmatoscom I plan on merging this PR soon. Anything I can do to help?

**Comment by mmatoscom** [comment]
Hi @weskerfoot , I am so sorry, I had an hectic week
will try to fix it this weekend
we cant go live without the correct parameters from your script exported to container ARGS

**Comment by weskerfoot** [comment]
No problem! I've been really busy too

**Comment by weskerfoot** [comment]
Once it's ready I am also going to start publishing images to Docker Hub

**Comment by mmatoscom** [comment]
> @mmatoscom I plan on merging this PR soon. Anything I can do to help?

My friend I am trying to export all options to the container, will try to fix this tomorrow, sorry for delay, have been really busy these days but interested in finish and merge. thanks

**Comment by weskerfoot** [comment]
@mmatoscom FYI my other branch https://github.com/weskerfoot/DeleteFB/pull/72 introduces a new flag `--conversations` that archives and deletes messenger convos.

**Comment by mmatoscom** [comment]
@weskerfoot  working on it today.

**Comment by mmatoscom** [comment]
@weskerfoot  is there a channel or messenger we could use to speak?

**Comment by weskerfoot** [comment]
@mmatoscom Do you use IRC? I am on Freenode most of the time. I can just create the channel `#deletefb`

**Comment by mmatoscom** [comment]
just joined there

**Comment by mmatoscom** [comment]
I have added the working files
kindly have a look when you have time
its just `git clone`, then `make`
we could do more from here, lets merge this working version before starting developing further
thanks =)

**Comment by weskerfoot** [comment]
Awesome! I'll try to take a look soon, thanks!

**Comment by weskerfoot** [comment]
I should be able to test it out and then suggest any potential changes soon.

**Comment by weskerfoot** [comment]
Sorry I've been really busy, I'll get to this today

**Comment by mmatoscom** [comment]
dont worry, I have been busy as well, take your time
cheers

**Comment by weskerfoot** [comment]
I'm building it at the moment. I think I'm going to have to figure out a workflow for building / releasing everything and uploading it to a docker registry.

**Comment by mmatoscom** [comment]
I could help with Travis CI

**Comment by weskerfoot** [comment]
@mmatoscom Travis CI would be fine to have, can you open a new issue for it?

**Pull request merged**
