### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by mmatoscom**
changes for travis ci

### CODE REVIEW

**Comment by mmatoscom** [comment]
@weskerfoot  bro I tried to cherry pick the last commit from a new branch but did something wrong
ok, CI has worked, you need to login at https://travis-ci.com, authorize it on github, then under settings create the secure vars for  ${REGISTRY_USER}, ${REGISTRY_PASS} and ${IMAGE_NAME}, before running the first pipeline. Anything else please ping me, cheers

**Comment by weskerfoot** [comment]
Awesome, I'll try to get it working. I don't actually have an account yet so I'll need to do that first.

**Comment by weskerfoot** [comment]
Created the account. Testing it out now.

**Comment by mmatoscom** [comment]
if you need anything let me know

**Comment by weskerfoot** [comment]
@mmatoscom I'm good. Just need to find some time to fine tune things a bit and figure out how it's all going to fit together in the larger picture. I'm going to have to fix up the documentation and everything I think to go along with this so it's clearer.

**Comment by weskerfoot** [comment]
Sorry for neglecting this. I should have free time this weekend to play around with it some more.

**Pull request merged**
