### PR TITLE
Remove log files

### PR DESCRIPTION
**Pull request by gwgundersen**
Don't version control log output files such as `deletefb.log`.

### CODE REVIEW

**Comment by weskerfoot** [comment]
This is fine but for some reason Github is complaining about conflicts. I'll try to fix it later.

**Comment by weskerfoot** [comment]
I think the `logging_conf.json` needs to stay

**Comment by gwgundersen** [comment]
I've updated my branch and kept `logging_conf.json`, and that seemed to resolve the conflicts.

**Comment by weskerfoot** [comment]
Looks good to me! Thanks for the help!

**Pull request merged**
