### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by ConnorSkees**
This kinda what I was imagining as far as having a logging system.

Also, I was unable to run it on Windows 10 and WSL Ubuntu when the imports were prepended with '.' (`from .tools.login import login`). Not sure if this is an error on my part, though.

### CODE REVIEW

**Comment by weskerfoot** [comment]
Thanks for figuring this out. The reason I used relative imports is so that calling the script directly doesn't break, because Python thinks you're not in a package. I would be ok with not supporting calling the .py file directly if it makes it easier to support Windows though. I don't think there's any reason to not just use `pip install --user` to run the program.

**Comment by weskerfoot** [comment]
Does `python -m deletefb.deletefb.py` still work?

**Comment by weskerfoot** [comment]
Could you just update the README to remove the bit here about `python -m`? https://github.com/weskerfoot/DeleteFB/blob/master/README.md#how-to-use-it

**Comment by ConnorSkees** [comment]
Oh I see. I was running it from the cloned directory just as `>>> deletefb.py`

Through Windows 10 prompt:
```
(base) C:\DeleteFB\deletefb>python -m deletefb.py
Traceback (most recent call last):
  File "C:\Users\Connor\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Connor\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\DeleteFB\deletefb\deletefb.py", line 9, in <module>
    from .tools.common import logger
ImportError: attempted relative import with no known parent package
```

I'm not sure why (Python directory structures are so confusing to me), but on WSL:
```
connorskees /mnt/c/DeleteFB/deletefb > python -m deletefb.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/mnt/c/DeleteFB/deletefb/deletefb.py", line 9, in <module>
    from .tools.common import logger
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by weskerfoot** [comment]
Oh, I think it was because `python -m deletefb.py` runs it as a module (which is fine), but the "package" is the directory `deletefb`, so it needs to somehow be running that inside a package, but it doesn't have a directory structure (which is how Python organizes packages obviously).

So you would get `ImportError: attempted relative import with no known parent package` when you just did `python -m deletefb.py` because it only knows about the module, but if you did `python -m deletefb.deletefb` it would have worked because it gets resolved to `deletefb/deletefb.py` (where the first part is the package and the second is the module).

That is probably just too confusing for people to understand, so I think it does make better sense your way. I just tested running `python deletefb/deletefb.py` directly and it seems to work, so let's keep it this way and update the docs I think.

**Comment by weskerfoot** [comment]
Looks good, thanks!

**Comment by weskerfoot** [comment]
@ConnorSkees I switched it back to the relative imports because I was having issues getting it to work with the `pip install --user .` flow. I think it works fine if you do `python -m deletefb.deletefb` in the virtualenv and I'd rather use that as the method there than try to work around not having relative imports.

**Comment by ConnorSkees** [comment]
Yeah that sounds good to me. Something I hadn't considered, though, is using
```
try:
    from .tools.common import logger
    from .tools.login import login
    from .tools.wall import delete_posts
    from .tools.likes import unlike_pages
except ImportError:
    from tools.common import logger
    from tools.login import login
    from tools.wall import delete_posts
    from tools.likes import unlike_pages
```
in deletefb.py

and 
```
try:
    from .deletefb import run_delete
except ImportError:
    from deletefb import run_delete
```
in \_\_main__.py

which actually allows it to be run from the DeleteFB directory using all of `python deletefb`, `python -m deletefb`, and `python -m deletefb.deletefb` as well as `deletefb.py` from the deletefb directory

**Pull request merged**
