### PR TITLE
rewrite of chromedriver download

### PR DESCRIPTION
**Pull request by whuji**
- Always pick the latest version of chromedriver
 - rewrited using requests instead of the old urllib package

### CODE REVIEW

**Comment by weskerfoot** [comment]
There's a specific way google recommends generating the chromedriver version

* First, construct a LATEST_RELEASE URL using Chrome's major version number.
* For example, with Chrome version 73.0.3683.86, use URL https://chromedriver.storage.googleapis.com/LATEST_RELEASE_73".
*  Try to download a small file from this URL. If it successful, the file contains the ChromeDriver version to use.
* If the above step failed, reduce the Chrome major version by 1 and try again.
* For example, with Chrome version 75.0.3745.4, use URL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_74"

I'll have to look over this and see what can be merged from the stuff I was working on. My issue was that in order to find the best version of it, you have to know what version of chrome is installed, and that's tricky to do on windows.

**Comment by weskerfoot** [comment]
I think for now it might be fine to just use the latest on windows, and I can pull from this branch and integrate it into what I was doing maybe

**Comment by whuji** [comment]
Maybe with wmic datafile get Version?  Did you try? I can implement it if you want, but I must find a Windows to test it.

**Comment by weskerfoot** [comment]
I can test it in a windows VM soon

**Comment by weskerfoot** [comment]
I've been fairly busy lately but I am going to try and do some work on this soon

**Comment by weskerfoot** [comment]
I've got this working on my other branch. Closing this one.

**Pull request closed without merging**
